# Generated by Django 4.1.4 on 2023-07-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drowsiness_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='license_id',
            field=models.CharField(default=2, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
