# Generated by Django 4.1.4 on 2023-07-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drowsiness_system', '0002_user_license_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static\\images\\driverdrowsiness.jpg')),
            ],
        ),
    ]
