# Generated by Django 4.1.4 on 2023-07-25 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drowsiness_system', '0003_imagemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
